# Style de code
kotlin.code.style=official

# KSP & Kotlin configuration
# Désactiver le daemon KSP règle souvent les erreurs 'ClassNotFoundException' sur CI
ksp.use.daemon=false
kotlin.mpp.applyDefaultHierarchyTemplate=true

# Gradle JVM Settings
# Fusion des deux lignes : 4Go de RAM est le minimum recommandé pour la compilation iOS/Kotlin Native
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2048M"

# Android configuration
android.nonTransitiveRClass=true
android.useAndroidX=true
